from datetime import datetime, timezone
from sqlalchemy import String, Text, Integer, DateTime, ForeignKey, Boolean
from sqlalchemy.orm import Mapped, mapped_column
from .database import Base

def now(): return datetime.now(timezone.utc)
class Task(Base):
    __tablename__="tasks"; id:Mapped[int]=mapped_column(primary_key=True); public_id:Mapped[str|None]=mapped_column(String(120),unique=True)
    title:Mapped[str]=mapped_column(String(255)); description:Mapped[str]=mapped_column(Text); normalized_requirement:Mapped[str|None]=mapped_column(Text)
    status:Mapped[str]=mapped_column(String(40),default="NEW",index=True); priority:Mapped[int]=mapped_column(Integer,default=0); project_path:Mapped[str]=mapped_column(Text)
    base_branch:Mapped[str]=mapped_column(String(255),default="main"); execution_branch:Mapped[str|None]=mapped_column(String(255)); created_by:Mapped[str]=mapped_column(String(100),default="local-user"); source:Mapped[str]=mapped_column(String(30),default="cli")
    plan_json:Mapped[str|None]=mapped_column(Text); acceptance_criteria_json:Mapped[str|None]=mapped_column(Text); retry_count:Mapped[int]=mapped_column(default=0); max_retries:Mapped[int]=mapped_column(default=2)
    paused_from:Mapped[str|None]=mapped_column(String(40)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now); approved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class SubTask(Base):
    __tablename__="subtasks"; id:Mapped[int]=mapped_column(primary_key=True); public_id:Mapped[str]=mapped_column(String(180),unique=True); task_id:Mapped[int]=mapped_column(ForeignKey("tasks.id")); key:Mapped[str|None]=mapped_column(String(40)); title:Mapped[str]=mapped_column(String(255)); description:Mapped[str]=mapped_column(Text); status:Mapped[str]=mapped_column(String(30),default="PENDING"); agent_type:Mapped[str]=mapped_column(String(30),default="mock"); role:Mapped[str]=mapped_column(String(30),default="implementation"); order_index:Mapped[int]=mapped_column(default=0); dependencies_json:Mapped[str]=mapped_column(Text,default="[]"); acceptance_criteria_json:Mapped[str]=mapped_column(Text,default="[]"); workspace_path:Mapped[str|None]=mapped_column(Text); result_summary:Mapped[str|None]=mapped_column(Text); retry_count:Mapped[int]=mapped_column(default=0); max_retries:Mapped[int]=mapped_column(default=2); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)
class Job(Base):
    __tablename__="jobs"; id:Mapped[int]=mapped_column(primary_key=True); public_id:Mapped[str]=mapped_column(String(180),unique=True); job_type:Mapped[str]=mapped_column(String(40)); task_id:Mapped[int]=mapped_column(ForeignKey("tasks.id")); subtask_id:Mapped[int|None]=mapped_column(ForeignKey("subtasks.id")); payload_json:Mapped[str]=mapped_column(Text,default="{}"); status:Mapped[str]=mapped_column(String(30),default="QUEUED",index=True); priority:Mapped[int]=mapped_column(default=0); attempts:Mapped[int]=mapped_column(default=0); max_attempts:Mapped[int]=mapped_column(default=3); available_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,index=True); locked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); locked_by:Mapped[str|None]=mapped_column(String(100)); heartbeat_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); last_error:Mapped[str|None]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)
class Approval(Base):
    __tablename__="approvals"; id:Mapped[int]=mapped_column(primary_key=True); task_id:Mapped[int]=mapped_column(ForeignKey("tasks.id")); approval_type:Mapped[str]=mapped_column(String(40),default="PLAN"); risk_level:Mapped[str]=mapped_column(String(20),default="medium"); request_reason:Mapped[str]=mapped_column(Text); request_payload_json:Mapped[str]=mapped_column(Text,default="{}"); status:Mapped[str]=mapped_column(String(20),default="PENDING"); requested_by:Mapped[str]=mapped_column(String(100),default="system"); approved_by:Mapped[str|None]=mapped_column(String(100)); source:Mapped[str]=mapped_column(String(20),default="cli"); comment:Mapped[str|None]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); resolved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class EventLog(Base):
    __tablename__="events"; id:Mapped[int]=mapped_column(primary_key=True); task_id:Mapped[int]=mapped_column(ForeignKey("tasks.id"),index=True); event_type:Mapped[str]=mapped_column(String(60)); actor_type:Mapped[str]=mapped_column(String(30)); actor_id:Mapped[str]=mapped_column(String(100)); payload_json:Mapped[str]=mapped_column(Text,default="{}"); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class AgentRun(Base):
    __tablename__="agent_runs"; id:Mapped[int]=mapped_column(primary_key=True); task_id:Mapped[int]=mapped_column(ForeignKey("tasks.id")); subtask_id:Mapped[int]=mapped_column(ForeignKey("subtasks.id")); agent_type:Mapped[str]=mapped_column(String(30)); command_json:Mapped[str]=mapped_column(Text,default="[]"); prompt:Mapped[str]=mapped_column(Text); status:Mapped[str]=mapped_column(String(30)); exit_code:Mapped[int|None]=mapped_column(); stdout_path:Mapped[str|None]=mapped_column(Text); stderr_path:Mapped[str|None]=mapped_column(Text); result_json:Mapped[str|None]=mapped_column(Text); started_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); finished_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class VerificationRun(Base):
    __tablename__="verification_runs"; id:Mapped[int]=mapped_column(primary_key=True); task_id:Mapped[int]=mapped_column(ForeignKey("tasks.id")); subtask_id:Mapped[int|None]=mapped_column(ForeignKey("subtasks.id")); command_json:Mapped[str]=mapped_column(Text); working_directory:Mapped[str]=mapped_column(Text); status:Mapped[str]=mapped_column(String(30)); exit_code:Mapped[int|None]=mapped_column(); passed:Mapped[bool]=mapped_column(Boolean,default=False); duration_ms:Mapped[int|None]=mapped_column(); stdout_path:Mapped[str|None]=mapped_column(Text); stderr_path:Mapped[str|None]=mapped_column(Text); summary:Mapped[str|None]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)


